[package]
name = "ckb-types"
version = "0.101.9-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
license = "MIT"
description = "Provides the essential types for CKB."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
bitflags = "1.0"
molecule = "=0.7.3"
ckb-fixed-hash = { path = "../fixed-hash", version = "= 0.101.9-pre" }
numext-fixed-uint = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
bytes = { version="1", features = ["serde"] }
merkle-cbt = "0.3"
ckb-occupied-capacity = { path = "../occupied-capacity", version = "= 0.101.9-pre" }
ckb-hash = { path = "../hash", version = "= 0.101.9-pre" }
ckb-channel = { path = "../channel", version = "= 0.101.9-pre" }
bit-vec = "0.6.3"
ckb-error = { path = "../../error", version = "= 0.101.9-pre" }
ckb-rational = { path = "../rational", version = "= 0.101.9-pre" }
once_cell = "1.8.0"
derive_more = { version = "0.99.0", default-features=false, features = ["display"] }

[dev-dependencies]
proptest = "1.0"
