[package]
name = "ckb-stop-handler"
version = "0.101.9-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
license = "MIT"
description = "TODO(doc): @keroro520 crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
parking_lot = "0.12"
ckb-logger = { path = "../logger", version = "= 0.101.9-pre" }
tokio = { version = "1", features = ["sync", "rt-multi-thread"] }
ckb-channel = { path = "../channel", version = "= 0.101.9-pre" }
